version: "3.8"

services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - websocket-server

  websocket-server:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-app
      - websocket-server
